on:
  issues:
    types: [opened, edited]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: A job to lint the issues
    steps:
      - name: lint the issues
        uses: KOLANICH-GHActions/KSFGHAction.py@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
